#!/usr/bin/env bash
#A Bash script that installs Nginx Server
#Configure the server to listen to port 80
#configure / at its root with a GET request using curl,
#returns a page that contains the string Hello World!
apt-get -y update
apt-get -y install nginx
ufw allow 'Nginx HTTP'
echo 'Hello World!' > /var/www/html/index.nginx-debian.html
service nginx start
