#!/usr/bin/env bash
#prints bad luck & good luck for 4th and 8th iteration respectively and "Best School" for other iterations

count=1

while [ $count -le 10 ]
do
	if [ $count -eq 4 ]; then
		echo "bad luck"
	elif [ $count -eq 8 ]; then
		echo "good luck"
	else
		echo "Best School"
	fi

	((count++))
done
